# Project information
site_name: OSSVerse
site_description: >-
  A revolutionary platform designed to connect businesses with reliable open source software service providers. Imagine an ecosystem where you can easily find, evaluate, and procure trusted open source solutions. That's the vision behind OSSVerse.

# Repository
repo_name: OSSVerse/OSSVerse
repo_url: https://github.com/OSSVerse/OSSVerse
edit_uri: ""

# Copyright
# #

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "bes_theme"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: bes_theme/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: bes_theme/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/icons/favicon.ico
  logo: assets/images/icons/favicon.ico
  icon:
    logo: logo


# # Plugins
# plugins:
#   - search
#   - redirects:
#       redirect_maps:
#         changelog/insiders.md: insiders/changelog.md
#         extensions/admonition.md: reference/admonitions.md
#         extensions/codehilite.md: reference/code-blocks.md
#         extensions/footnotes.md: reference/footnotes.md
#         extensions/metadata.md: reference/meta-tags.md
#         extensions/permalinks.md: setup/setting-up-navigation.md #permalink
#         extensions/pymdown.md: reference/admonitions.md
#         plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
#         plugins/search.md: setup/setting-up-site-search.md
#         releases/4.md: upgrading.md #upgrading-from-4x-to-5x
#         releases/5.md: upgrading.md #upgrading-from-3x-to-4x
#         releases/changelog.md: changelog.md
#         setup/adding-social-links.md: setup/setting-up-the-footer.md
#         sponsorship.md: insiders/index.md
#   - minify:
#       minify_html: true

# Customization
# extra:
#   analytics:
#     provider: google
#     # property: !ENV GOOGLE_ANALYTICS_KEY
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/squidfunk
#     - icon: fontawesome/brands/gitter
#       link: https://gitter.im/squidfunk/Be-Secure
#     - icon: fontawesome/brands/docker
#       link: https://hub.docker.com/r/squidfunk/Be-Secure/
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/squidfunk
#     - icon: fontawesome/brands/linkedin
#       link: https://linkedin.com/in/squidfunk/
#     - icon: fontawesome/brands/instagram
#       link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home: index.md
  - Platform:
    - OSSVerse: "concepts/overview.md"
    - Participants:
      - Seller:
        - OASP: "concepts/oss-assurance-provider.md"
      - Buyer:
        - OSS Producer: "concepts/oss-producer.md"
        - OSS Consumer: "concepts/oss-consumer.md"
        - OSS Distributor: "concepts/oss-distributor.md"
      - Marketplace Operator: "concepts/ossverse-operator.md"
#  - How To Join:
#    - Sellers (OASP): "how-to-join/oss-assurance-provider.md"
#    - Buyers (Business): "how-to-join/bes-lab.md"
#  - FAQ: "concepts/faq.md"
  - Developer:
#    - Getting Started: "developer/overview.md"
#    - Tech Stack: "developer/tech-stack.md" 
#    - Architecture: "developer/target-architecture.md"
    - Projects: "developer/projects.md"
#    - API Reference: 
#      - Buyer App: "developer/api-reference/ossverse-buyer-app.md"
#      - OASP Seller App: "developer/api-reference/oasp-seller-app.md"
#    - OSSVerse-In-A-Box: "developer/ossverse-in-a-box.md"
#  - Community:
#    - Overview: "community/index.md"
