# ref link: https://alinex.gitlab.io/env/mkdocs/
#===================================================================================#
# Site Information
#===================================================================================#
site_name: binbash Leverage™
repo_name: "OSSVerse/OSSVerse"
repo_url: https://github.com/OSSVerse/OSSVerse
site_url: https://leverage.binbash.co/
site_description: OSSVerse Documentation
site_author: binbash
copyright: Copyright &copy; 2017-2023 <a href="https://www.binbash.co">binbash</a>

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: material
  language: en
  #logo: assets/images/logos/binbash-icon.png
  icon: # https://www.materialpalette.com/icons
    logo: material/book-open-page-variant
  favicon: assets/images/logos/favicon.ico
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - header.autohide
    - content.action.edit
    #- content.tabs.link #Insiders only so far
    - content.code.annotate
  palette: # https://www.materialpalette.com/colors
    - scheme: default
      #primary: "teal" # comment to replace by /docs/assets/stylesheets
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      #primary: "teal" # comment to replace by /docs/assets/stylesheets
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  include_sidebar: true

extra:
  #generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

## Temporally only available for Insiders
## (https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#was-this-page-helpful)
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks for your feedback! Help us improve this page by
#            using our <a href="..." target=_blank>feedback form</a>.

  social:
    - icon: material/home
      link: 'https://www.binbash.co'
    - icon: material/github
      link: 'https://github.com/binbashar'
    - icon: material/linkedin
      link: 'https://www.linkedin.com/company/binbash'
    - icon: material/slack
      link: 'https://join.slack.com/t/binbashar/shared_invite/zt-fw1692b6-9k4ADsWJ47lKacszphXM1w'
    - icon: material/youtube
      link: 'https://www.youtube.com/channel/UCUjQ3duzxQB_VtNsKNqPwDA/playlists'
    - icon: fontawesome/brands/medium
      link: 'https://medium.com/binbash-inc'
    - icon: material/twitter
      link: 'https://twitter.com/binbash_devops'
    - icon: material/docker
      link: 'https://hub.docker.com/orgs/binbash'

  alternate:
    # Switch to English
    - name: English
      #link: https://leverage.binbash.co
      link: /
      lang: en

    # Switch to Spanish
    - name: Spanish
      #link: https://leverage.binbash.co/es/
      link: /es
      lang: es

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

plugins:
  - search
#  - awesome-pages

extra_css:
    - assets/stylesheets/extra.css

#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home:
    - Home: "index.md"
    - Welcome: "concepts/index.md"
    - First steps: "try-leverage/index.md"
    - How it works: "how-it-works/ref-architecture/index.md"
    - User guide: "guide/index.md"
    - Work with us: "work-with-us/index.md"
    - License: "license.md"

  - Concepts:
    - Index: "concepts/index.md"
    - What is OSSVerse?: "concepts/what-is-ossverse.md"
    - Why OSSVerse?: "concepts/why-ossverse.md"
    - What can OSSVerse do for you?: "concepts/what-ossverse-can-do-for-you.md"
    - Tech Stack: "concepts/tech-stack.md"
    - Next Steps: "concepts/next-steps.md"

  - Getting Started:
    - Index: "getting-started/index.md"
    - Creating your AWS Management account: "getting-started/aws-account-setup.md"
    - Install Leverage CLI: "getting-started/local-setup.md"
    - Create a Leverage project: "getting-started/leverage-project-setup.md"
    - Configure the Management account: "getting-started/management-account.md"
    - Enable SSO: "getting-started/enabling-sso.md"
    - Configure the Security and Shared accounts: "getting-started/security-and-shared-accounts.md"
    - Post-deployment: "getting-started/post-deployment.md"
    - Add more AWS Accounts: "getting-started/add-aws-accounts.md"

  - Guide:
    - Index: "guide/index.md"
    - Architecture:
      - Overview: "guide/architecture/overview.md"
      - Project Structure: "guide/architecture/dir-structure.md"
      - Configuration: "guide/architecture/configuration.md"
    - Releases:
      - Releases and Versions: "guide/releases/releases-and-versions.md"
      - Versions compatibility matrix: "guide/releases/versions-compatibility-matrix.md"
    - OSSVerse-in-a-Box:
      - Credentials: "guide/ossverse-in-a-box/credentials.md"
      - Workflow: "guide/ossverse-in-a-box/workflow.md"
      - Terraform State: "guide/ossverse-in-a-box/tf-state.md"
      - References: "guide/ossverse-in-a-box/references.md"
    - Troubleshooting:
      - Overview: "guide/troubleshooting/index.md"
      - General: "guide/troubleshooting/general.md"
      - Credentials: "guide/troubleshooting/credentials.md"
  - Join OSSVerse:
      - Overview: "join-ossverse/index.md"
      - Support: "join-ossverse/support.md"
      - Contribute: "join-ossverse/contribute.md"
      - Team: "join-ossverse/team.md"
      - Testimonials: "join-ossverse/testimonials.md"
      - FAQs: "join-ossverse/faqs.md"
      - Contact Us: "join-ossverse/contact.md"
