site_name: OSSVerse

nav:
  - Home: index.md
  - Overview: overview.md
  - Guides: 
    - Architecture: target-architecture.md
    - Features: features.md
    - Assurance Provider: assurance-provider.md
    - Open Source Consumer: oss-consumer.md 
  - About: about.md
