# Project information
site_name: OSSVerse
site_description: >-
  A Trustworthy Marketplace for Open-Source Assurance Service Providers (OASP) backed by a thriving open-source security community. Affordable and timely access to vendor neutral security services for organizations producing and consuming open-source. OASP led open source assurance service delivery would give full control over their open source components.

# Repository
repo_name: OSSVerse/OSSVerse
repo_url: https://github.com/OSSVerse/OSSVerse
edit_uri: ""

# Copyright
# #

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "bes_theme"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: bes_theme/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: bes_theme/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  # logo: assets/favicon.png
  icon:
    logo: logo

# # Plugins
# plugins:
#   - search
#   - redirects:
#       redirect_maps:
#         changelog/insiders.md: insiders/changelog.md
#         extensions/admonition.md: reference/admonitions.md
#         extensions/codehilite.md: reference/code-blocks.md
#         extensions/footnotes.md: reference/footnotes.md
#         extensions/metadata.md: reference/meta-tags.md
#         extensions/permalinks.md: setup/setting-up-navigation.md #permalink
#         extensions/pymdown.md: reference/admonitions.md
#         plugins/revision-date.md: setup/adding-a-git-repository.md #revision-date
#         plugins/search.md: setup/setting-up-site-search.md
#         releases/4.md: upgrading.md #upgrading-from-4x-to-5x
#         releases/5.md: upgrading.md #upgrading-from-3x-to-4x
#         releases/changelog.md: changelog.md
#         setup/adding-social-links.md: setup/setting-up-the-footer.md
#         sponsorship.md: insiders/index.md
#   - minify:
#       minify_html: true

# Customization
# extra:
#   analytics:
#     provider: google
#     # property: !ENV GOOGLE_ANALYTICS_KEY
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/squidfunk
#     - icon: fontawesome/brands/gitter
#       link: https://gitter.im/squidfunk/Be-Secure
#     - icon: fontawesome/brands/docker
#       link: https://hub.docker.com/r/squidfunk/Be-Secure/
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/squidfunk
#     - icon: fontawesome/brands/linkedin
#       link: https://linkedin.com/in/squidfunk/
#     - icon: fontawesome/brands/instagram
#       link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      # insert a blank space before the character
      permalink: " ¶"

  # - admonition
  # - abbr
  # - attr_list
  # - def_list
  # - footnotes
  # - meta
  # - md_in_html
  # - toc:
  #     permalink: true
  # - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:bes_themex.emoji.twemoji
  #     emoji_generator: !!python/name:bes_themex.emoji.to_svg
  # - pymdownx.highlight
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: Be-Secure
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid-experimental
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.tabbed
  # - pymdownx.tasklist:
  #     custom_checkbox: true
  # - pymdownx.tilde

# Page tree


#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home: index.md
  - Concepts:
    - Overview: "concepts/index.md"
    - What is OSSVerse?: "concepts/what-is-ossverse.md"
    - Why OSSVerse?: "concepts/why-ossverse.md"
    - What can OSSVerse do for you?: "concepts/what-ossverse-can-do-for-you.md"
    - Tech Stack: "concepts/tech-stack.md"
    - Next Steps: "concepts/next-steps.md"

  - Getting Started:
    - Overview: "getting-started/index.md"
  #  - Creating your AWS Management account: "getting-started/aws-account-setup.md"
  #  - Install Leverage CLI: "getting-started/local-setup.md"
  #  - Create a Leverage project: "getting-started/leverage-project-setup.md"
  #  - Configure the Management account: "getting-started/management-account.md"
  #  - Enable SSO: "getting-started/enabling-sso.md"
  #  - Configure the Security and Shared accounts: "getting-started/security-and-shared-accounts.md"
  #  - Post-deployment: "getting-started/post-deployment.md"
  #  - Add more AWS Accounts: "getting-started/add-aws-accounts.md"

  - Developer Guide:
    - Overview: "guide/index.md"
  #  - Architecture:
  #    - Overview: "guide/architecture/overview.md"
  #    - Project Structure: "guide/architecture/dir-structure.md"
  #    - Configuration: "guide/architecture/configuration.md"
  #  - Releases:
  #    - Releases and Versions: "guide/releases/releases-and-versions.md"
  #    - Versions compatibility matrix: "guide/releases/versions-compatibility-matrix.md"
  #  - OSSVerse-in-a-Box:
  #    - Credentials: "guide/ossverse-in-a-box/credentials.md"
  #    - Workflow: "guide/ossverse-in-a-box/workflow.md"
  #    - Terraform State: "guide/ossverse-in-a-box/tf-state.md"
  #    - References: "guide/ossverse-in-a-box/references.md"
  #  - Troubleshooting:
  #    - Overview: "guide/troubleshooting/index.md"
  #    - General: "guide/troubleshooting/general.md"
  #    - Credentials: "guide/troubleshooting/credentials.md"
  - Join OSSVerse:
      - Overview: "join-ossverse/index.md"
  #    - Support: "join-ossverse/support.md"
  #    - Contribute: "join-ossverse/contribute.md"
  #    - Team: "join-ossverse/team.md"
  #    - Testimonials: "join-ossverse/testimonials.md"
  #    - FAQs: "join-ossverse/faqs.md"
  #    - Contact Us: "join-ossverse/contact.md"




  
