@startuml

skin rose

title "Sequence diagram - OASPs service Discovery"

actor "OSSConsumer" as Buyer

Buyer -> OSSVerse.com: Search catalogue
OSSVerse.com -> "Network Gateway": /Search
database "OASP Network Registry"
"Network Gateway" -> "OASP Network Registry": lookup
"OASP Network Registry" -> "Network Gateway": 200
"Network Gateway" -> OSSVerse.com: ACK

"Network Gateway" -> "OASP(1)": /Search
"Network Gateway" -> "OASP(2)": /Search
"Network Gateway" -> "OASP(n)": /Search

"OASP(1)" -> "Network Gateway": /On_Search - callback
"OASP(2)" -> "Network Gateway": /On_Search - callback
"OASP(n)" -> "Network Gateway": /On_Search - callback

"Network Gateway" -> "Network Gateway": Catalogue Aggregation of all OASPs
"Network Gateway" -> OSSVerse.com: /On_Search - callback


OSSVerse.com -> Buyer: Display OASPs offerings

@enduml