@startuml

actor "Bosch_Lab" as Actor


Actor -> OSSVerse_Interface: Create Account
Actor -> OSSVerse_Interface: Select Roles(OASP, Buyer, Seller)
OSSVerse_Interface -> OSSVerse_API_Gateway: Call registration API
OSSVerse_API_Gateway -> OSSVerse_IAM_keycloak: Sends the user data to Keycloak for creating a new user account

OSSVerse_API_Gateway -> OSSVerse_search_opensearch: If successful, the API stores essential user profile (e.g., user ID, email etc) in OpenSearch 


@enduml
