@startuml

skin rose

actor Tokomo as Tokomo
Tokomo -> Tokomo: Tokomo Plans to on-board on OSSVerse as a buyer
Tokomo -> Tokomo: To become a buyer on OSSVerse, Tokomo needs to Compliant with BAP protocol

Tokomo -> OSSVerseRegistry: HTTPS - Tokomo initiate the registration process using Registry API( NO UI involved ) with Public IP - and share info like (BAP details, BAP offerings, BAP API end-points)
OSSVerseRegistry -> Tokomo: Response with "Subscribed" success, ID, Key and other relevant info required for further transaction
OSSVerseRegistry -> OSSVerseRegistry: Persist meta data

Tokomo -> OSSVerse_Marketplace: Tokomo comes to "OSSVerse Marketplace UI" and start using the platform using keys received from post "successfull registration" to buys the services & offerings provided by seller Apps


@enduml
