@startuml

skin rose

actor Tokomo as Tokomo
Tokomo -> Tokomo: Tokomo is now a BAP on the OSSVerse Marketplace after successful BAP registration.

Tokomo -> OSSVerse_Marketplace: Login to platform
Tokomo -> OSSVerse_Marketplace: Search for an OSS & Offerings

OSSVerse_Marketplace -> OSSVerse_Gateway: sends a search query to the gateway, specifying the desired product or service, location, and other preferences
OSSVerse_Gateway -> OSSVerse_Registry: The gateway queries the registry to identify potential BPPs matching the search criteria

OSSVerse_Gateway-> Lab_O31E: The gateway forwards the search request to the identified BPPs
Lab_O31E -> OSSVerse_Gateway: All BPPs Response data comes to gateway
OSSVerse_Gateway -> OSSVerse_Gateway: Gateway Aggregate the results

OSSVerse_Gateway -> OSSVerse_Marketplace: Aggregates responses from BPPs and returns them to the OSSVerse_Marketplace

Tokomo -> OSSVerse_Marketplace: Verify the response and generate further events

@enduml
