@startuml

skin rose
actor Greenhill as Greenhill
Greenhill -> Greenhill: Greenhill plans to subscribe to OSSVerse as OSS producer


Lab_O31E -> Lab_O31E: Lab_O31E - compliant with the Beckn BPP protocol
actor Greenhill as Greenhill
OSSVerseRegistry -> OSSVerseRegistry: domain name, SSL certificates, Nginx, Reverse proxy 


Greenhill -> Greenhill: Greenhill considers Lab_O31E as their BPP implementation choice
Greenhill -> Lab_O31E: Greenhill requests the setup of Lab_O31E using Be-Secure
Greenhill -> Greenhill: Greenhill completes the setup of Lab_O31E in their environment
Lab_O31E -> Greenhill: Greenhill becomes BPP compliant
Lab_O31E -> Greenhill: Greenhill now operates the 'Lab_O31E' instance within their environment
Greenhill -> Greenhill: Greenhill is now ready to initiate a BPP subscription to OSSVerse
Greenhill -> OSSVerseRegistry: HTTPS - Greenhill initiate the registration process using Registry API( NO UI involved ) with Public IP - and share info like (BPP details, BPP offerings, BPP API end-points)

OSSVerseRegistry -> OSSVerseRegistry: validate the request data, register and generate "private key"
OSSVerseRegistry -> Greenhill: Response with "Subscribed" success, ID, Key and other relevant info required for further transaction

Greenhill -> Lab_O31E: Greenhill Expose their services through Beckn-compliant APIs of Lab_O31E.
Lab_O31E -> Lab_O31E: Lab_O31E as BPP is ready to serve the incoming request from Marketplace

@enduml